default:
  image: haskell:9

variables:
  CABAL_DIR: ${CI_PROJECT_DIR}/.cabal

cache:
  paths:
    - .cabal

stages:
  - build
  - test

.build:
  stage: build
  before_script:
    - cabal update
    - cabal build --only-dependencies --enable-tests
  script:
    - cabal build
  artifacts:
    paths:
      - dist-newstyle/

build-8:
  extends: .build
  image: haskell:8

build-9:
  extends: .build
  image: haskell:9

haddock:
  stage: test
  script:
    - cabal haddock

unit-test:
  stage: test
  before_script:
    - mkdir -p $HOME/.cabal/bin
    - curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20211114/cabal-docspec-0.0.0.20211114.xz > cabal-docspec.xz
    - echo 'e224700d9e8c9ec7ec6bc3f542ba433cd9925a5d356676c62a9bd1f2c8be8f8a  cabal-docspec.xz' | sha256sum -c -
    - xz -d < cabal-docspec.xz > $HOME/.cabal/bin/cabal-docspec
    - rm -f cabal-docspec.xz
    - chmod a+x $HOME/.cabal/bin/cabal-docspec
    - cabal-docspec --version
  script:
    - cabal build --flag "+test"
    - cabal-docspec --check-properties --property-variables "d i j r s u v w x y z" --timeout 20
